name: HN21 Auto Start

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout private script repository
        uses: actions/checkout@v4
        with:
          repository: kamanmuez/HN21-Auto-Start  # 私库地址
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: scripts

      - name: Start Server
        working-directory: scripts
        run: |
          chmod +x start.sh
          ./start.sh

      - name: Clean up old workflow runs
        if: always()
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 86400  # 删除24小时前的记录
