name: HN21 Auto Start

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout private script repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/HN21-Auto-Start  # 私库地址
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: scripts

      - name: Start Server
        working-directory: scripts
        run: |
          chmod +x start.sh
          ./start.sh
